### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by mbumpalumpa** [humhub/text-editor#18]
@luke-, here is my suggestion for a use-case scenario for the module. I opted to support rolling out a new email signature as it seemed to be the only viable scenario to me, rather than some log file. But if you want, I can try to create a logical scenario where a log file would be applicable for Omrade :D. In my opinion, if someone sees HTML code, it should be enough to indicate that this isn't a word replacement, but let me know what you think.

SS1
![screenshot1](https://github.com/humhub/text-editor/assets/92554196/f45f04ff-1780-44d9-ae32-26ab6b07df8c)

SS2
![screenshot2](https://github.com/humhub/text-editor/assets/92554196/832ae4a3-5df6-42ef-a927-5ed9ad650f6d)

SS3
![screenshot3](https://github.com/humhub/text-editor/assets/92554196/997dd6c0-137b-420c-b9b9-fcb807a7e065)

SS4
![screenshot4](https://github.com/humhub/text-editor/assets/92554196/f23b14dd-efc3-42b7-8baf-580bf44a6758)

SS5
![screenshot5](https://github.com/humhub/text-editor/assets/92554196/205d47c1-e966-4a7c-a399-c57bec9197eb)

SS6
![screenshot6](https://github.com/humhub/text-editor/assets/92554196/b3504be0-2b7f-48a8-8b5b-e9e587bbf29c)

SS7
![screenshot7](https://github.com/humhub/text-editor/assets/92554196/87f3e98e-5481-4436-a4d6-96d579b0a90b)

**Comment by ArchBlood** [comment]
> @luke- Is there a way that we can also allow users to view PDFs with it in the future?

@Semir1212, I'm not sure exactly about adding PDFs as they are considered binary not text files, but it's not impossible, the real issue would be being able to edit such files, I'd recommend a similar approach with xml and only allowing download and not editing. 🤔

Here's some examples of how I've implemented it using #31 as a base;

![Screenshot_1](https://github.com/user-attachments/assets/3e6b3ac9-e877-4a7f-987f-e62e1953f6aa)
![Screenshot_2](https://github.com/user-attachments/assets/c7d6591b-39ea-4c62-9762-7b3e626eba6f)
![Screenshot_3](https://github.com/user-attachments/assets/40f08f49-0599-4df3-8dc6-10067e0f0c8e)
![Screenshot_4](https://github.com/user-attachments/assets/4ddccb4a-d6da-4c9b-a8fb-94ef440ab95f)

So to answer your question, yes it is very possible to do this as well as create PDFs with the editor, is it really recommended or needed, probably not as all major browsers support PDF view by default.

**Comment by luke-** [comment]
@ArchBlood Yes, we are planning our own PDF viewer module.

@mbumpalumpa @Semir1212 Can we finalize the screenshots and texts?

**Comment by Semir1212** [comment]
Passt @mbumpalumpa
